name: stellar
version: 0.3.2

description: Stellar client library for the Dart language.
author: Jeff Lee <jspschool@gmail.com>
homepage: https://github.com/jspschool/dart-stellar-sdk

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  convert: ^2.0.2
  crypto: ^2.0.6
  eventsource: ^0.2.1
  fixnum: ^0.10.9
  http: ^0.11.3+17
  tweetnacl: ^0.3.1

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
